### ISSUE TITLE
Usage with useInfiniteQuery

### ISSUE THREAD

**Issue by rodgeTech** [lukemorales/query-key-factory#27]
Hi,

Awesome library, been doing a lot of refactoring using this package...

Is it possible to use this along with the `useInfiniteQuery` hook? Haven't been able to find any examples to do so.

Thanks!

**Comment by lukemorales** [comment]
Thanks for the feedback @rodgeTech, I really appreciate the compliment and I'm glad it's being useful.

Yes, you definitely can use it with `useInfiniteQuery`, here's an example: https://codesandbox.io/s/compassionate-resonance-nxt2tp?file=/pages/index.js

**Comment by rodgeTech** [comment]
Oh great, many thanks!
