### ISSUE TITLE
Allow all query options within query definition (i.e. besides just queryKey, queryFn)

### ISSUE THREAD

**Issue by codebycarlos** [lukemorales/query-key-factory#36]
What do you think about allowing all useQuery options, in order to allow more complex definitions? 

For instance, if we wanted to always run this detail query with refetchOnMount set to 'always':

```
  export const users = createQueryKeys('users', {
    detail: (userId: string) => ({
      queryKey: [userId],
      queryFn: () => api.getUser(userId),
    }),
  });
```

to 

```
  export const users = createQueryKeys('users', {
    detail: (userId: string) => ({
      queryKey: [userId],
      queryFn: () => api.getUser(userId),
      refetchOnMount: 'always', // add refetchOnMount set to 'always'
      ...more useQuery options here...
    }),
  });
```

And so on..

**Comment by lukemorales** [comment]
Thanks for the great ideas @codebycarlos.

The suggestion is pretty good, but I need to sleep on the idea a little bit. It would be great to have all the query set up in there, but I'm not sure it introduces responsibilities beyond to what was intended for this lib.
If we get to the point of having all of this inside the lib, we might as well just return custom hooks? Feels like a natural path, but then there's already `react-query-kit` as a solution for that...

**Comment by panukettu** [comment]
+1

Stumbled across this lib recently and refactored one project to use it.
I did define all my queries thinking this was possible:

```
export const getSomeQueryDefinition = (filters: BaseFilter = filter.base()) => ({
  queryKey: [{ filters }] as const,
  queryFn: () => fetchSomeData(filters),
  options: {
    return {
      enabled: !!filters.foo && someComplexCheck(filters.bar),
      staleTime: 8000,
    }
  },
})

...

export const queries = createQueryKeyStore({
  foo: { 
    myQuery: getSomeQueryDefinition,
  }
})
```

anyways thanks for making this lib 👍🏻
