### ISSUE TITLE
Overwriting global isArray definition causes issues

### ISSUE THREAD

**Issue by JanStevens** [lukemorales/query-key-factory#43]
Hi,

I noticed that the following code causes issues in places where I already use `Array.isArray`

https://github.com/lukemorales/query-key-factory/blob/4d56c4a341196e7d02ed44fbd325493298ad2f70/src/internals/types.ts#L1-L5

Example, when using MUI v5, its typical to pass around the `sx` prop and spread it (docs: https://mui.com/system/getting-started/the-sx-prop/#passing-the-sx-prop)

Example:

<img width="596" alt="Screenshot 2023-01-09 at 11 38 02" src="https://user-images.githubusercontent.com/1540483/211289521-a5d10c70-2e60-4852-974a-f4146296e8c0.png">

When I comment out the redeclaration of `Array.isArray` I don't have the above errors anymore.

**Comment by lukemorales** [comment]
Thanks for bringing that up @JanStevens, I'll prepare a new release that fixes it
