### ISSUE TITLE
Support useMutation

### ISSUE THREAD

**Issue by mc-petry** [lukemorales/query-key-factory#49]
I want to be able to do something like that:
```tsx
const users = createQueryKeys('users', {
  list: null,
  editing: (id: string) => ({
    mutationKey: [id],
    mutationFn: ...
  }),
})

const { isLoading, mutate } = useMutation({
   ...users.editing(data.id),
   onSuccess() {}
})
```

I needed this to be able to use [useIsMutating](https://tanstack.com/query/v4/docs/react/reference/useIsMutating) hook.

**Comment by lukemorales** [comment]
This shouldn't be very complicated to implement, we only need to expose a new function `createMutationKeys` with the same signature as `createQueryKeys` but changing `queryFn` and `queryKey` to `mutationFn` and `mutationKey`.
Would you like to contribute to that with a PR @mc-petry ?

**Comment by lukemorales** [comment]
@mc-petry support for mutations is now available in https://github.com/lukemorales/query-key-factory/releases/tag/v1.2.0

Shoutout to @s-bondarenko for the contribution!

**Comment by tastyqbit** [comment]
Hi @lukemorales, would it be possible to create an example in the readme, I am unsure of how to use this in the way I would like - my goal is to mutate a peice of state that I can then save the result in a specific react-query key. Is this possible?
