### ISSUE TITLE
Error: Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by MshHooman** [lukemorales/query-key-factory#53]
Hi,

I'm trying to use the package but faced this error when I want to start the project.

important dependencies:
```
"@babel/core": "7.12.3",
"@lukemorales/query-key-factory": "^1.1.0",
"react": "^17.0.1",
"react-dom": "^17.0.1",
"@tanstack/react-query": "^4.24.4",
"webpack": "4.44.2",
```
plus that the project is ejected from CRA.

source code:
```
import { createQueryKeys } from '@lukemorales/query-key-factory';
export const usersKeys = createQueryKeys('users');
```

Error: 

```
./node_modules/@lukemorales/query-key-factory/dist/index.mjs 67:37
Module parse failed: Unexpected token (67:37)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|         } : void 0)
|       },
>           a = [...n, ...(r.queryKey ?? [])],
|           y = {
|         queryKey: a,

```

do you have any idea about what `loader` should I import or what makes this problem?

**Comment by lukemorales** [comment]
@MshHooman it seems that it's not being able to compile the `??` operator? If that's really the case, you can try to use this loader: https://babeljs.io/docs/babel-plugin-proposal-nullish-coalescing-operator

**Comment by gbyesiltas** [comment]
I have the same issue on Nuxt 2, error points to the same line. I tried adding the babel plugin but may not be doing it correctly because it didn't work. I'll try to figure it out and update you guys here

**Comment by lukemorales** [comment]
@gbyesiltas thanks for sharing the fix!
