### ISSUE TITLE
Allow to use bigint in queryKey

### ISSUE THREAD

**Issue by mc-petry** [lukemorales/query-key-factory#56]
**Actual:**
```tsx
createQueryKeys('users', {
  byId: (id: bigint) => ({
    queryKey: [id],
    queryFn: () => getUser({ id }),
  }),
})
```
We got an error: `Type '[bigint]' is not assignable to type 'KeyTuple'.`

**Expected result: no error**
This must be allowed case since we can override [queryKeyHashFn](https://tanstack.com/query/v4/docs/react/reference/useQuery).

**Comment by lukemorales** [comment]
@mc-petry sorry for the long waiting, but [v1.3.0](https://github.com/lukemorales/query-key-factory/releases/tag/v1.3.0) has been released and `bigInt` is now accepted as a valid value
