### ISSUE TITLE
Taking into account `select` option

### ISSUE THREAD

**Issue by ruudandriessen** [lukemorales/query-key-factory#69]
Part of the options in tanstack query is the [select property](https://tanstack.com/query/v4/docs/react/reference/useQuery). 

We were in the process of moving towards using query-key-factory, however we ran into typing issues since this property isn't being taken into account. Essentially, if select is defined, the `ReturnType` of select should be used instead of the return type of `queryFn`. We're using `select` in order to have cache hits even though data is transformed in different matters for differing use cases.

Example:

```ts
const items = createQueryKeys('items', {
    list: {
        queryFn: api.getListOfItems<ItemResponse>(),
        select: (response): MappedType => response.map(someThingThatChangesTheType),
    },
});
```

The expectation here would be that when using `useQuery(items.list)` the `data` property would be of type `MappedType`. Instead we found it's still `ItemResponse.

If I can get some pointers, I can also attempt a PR myself in order to clean up the types.

**Comment by lukemorales** [comment]
@ruudandriessen what exactly is your issue? you can have something like this work normally: `useQuery({ ...items.list, select: (response) => response.map(someThingThatChangesTheType) })`.

Are you trying to create custom hooks with generics? If so, I just released in the past couple of days a utility type `TypedUseQueryOptions` that should help you achieve that more easily:

```ts
import { createQueryKeys, TypedUseQueryOptions } from '@lukemorales/query-key-factory'

const items = createQueryKeys('items', {
    list: {
        queryKey: null,
        queryFn: api.getListOfItems<ItemResponse>,
    },
});

const useCustomQuery = <Data = ItemResponse>(options?: TypedUseQueryOptions<typeof items.list, Data>) => {
  return useQuery({ ...options, ...items.list });
}
```

**Comment by lukemorales** [comment]
@ruudandriessen thanks for bringing this to my attention, I've release [v1.3.2](https://github.com/lukemorales/query-key-factory/releases/tag/v1.3.2) that should block `select` and any other foreign keys from being added

**Comment by ruudandriessen** [comment]
> @ruudandriessen thanks for bringing this to my attention, I've release [v1.3.2](https://github.com/lukemorales/query-key-factory/releases/tag/v1.3.2) that should block `select` and any other foreign keys from being added

Great! Thanks for the quick response and clarifications @lukemorales 😄
