### ISSUE TITLE
Support for more nesting

### ISSUE THREAD

**Issue by SangJunBak** [lukemorales/query-key-factory#81]
It seems like the current API exposes only three levels of nesting (the definition for createQueryKeys, the sub-queries defined in createQueryKeys's schema, and the contextQueries property).

Assuming I want to generate the following nested query key structure:
```
region('region'): {
  todos('region', 'todos'): {
    detail('region', 'todos', 'detail'): (id) => {
      queryKey: ('region', 'todos', 'detail', id)
    },
    list('region', 'todos', 'list'): (filters) => {
      queryKey: ('region', 'todos', 'list', filters),
      search: (limit) => {
        queryKey: ('region', 'todos', 'list', filters, limit)
      }
    }
  },
  users('regions', 'users'): {
    ...
  }
}
```
And I want to compose `todos` and `users` using createQueryKey. Is it possible to do something like:
```
todos = createQueryKeys('todos', ...)
users = createQueryKeys('users', ...)

region = createQueryKeys('regions', 
  contextQueries: mergeQueryKeys(todos, users)
);
```
?

Ideally I want the API when getting the keys to look like:
```
useQuery(region.list(filters).search(limit)) // ['region', 'list', filters, 'search', limit]

```

**Comment by lukemorales** [comment]
Hi @SangJunBak, from what I can see this should be already possible with the current API:

```ts
const keys = createQueryKeys('region', {
  todos: {
    queryKey: null,
    contextQueries: {
      detail: (id) => ({
        queryKey: [id],
        {...}
      }),
      list: (filters) => {...}
    }
  }, 
}
```

LMK if I'm missing something

**Comment by SangJunBak** [comment]
Ah I didn't realize you can next context queries within context queries. Thanks for the help!
